location_data = [
    {'id': '1', 'name': 'Lagos', 'zone': "+1"},
    {'id': '2', 'name': 'Nairobi', 'zone': "+3"},
    {'id': '3', 'name': 'Kampala', 'zone': "+3"},
    {'id': '4', 'name': 'Kigali', 'zone': "+3"},
]
role_data = [
    {'id': '1', 'name': 'Administrator'},
    {'id': '2', 'name': 'user'},
]

user_role_data = [
    {'role_id': '1', 'user_id': '-LG__88sozO1OGrqda2z'},
    {'role_id': '1', 'user_id': '-K_djydLXD3FE_w141iJ'},
]

permission_data = [
    {'id': '1', 'name': 'view_menu', 'role_id': '1', 'keyword': 'view_menu'},
    {'id': '2', 'name': 'delete_vendor', 'role_id': '1', 'keyword': 'delete_vendor'},
    {'id': '3', 'name': 'view_ratings', 'role_id': '1', 'keyword': 'view_ratings'},
    {'id': '4', 'name': 'create_roles', 'role_id': '1', 'keyword': 'create_roles'},
    {'id': '5', 'name': 'view_roles', 'role_id': '1', 'keyword': 'view_roles'},
    {'id': '6', 'name': 'delete_engagement', 'role_id': '1', 'keyword': 'delete_engagement'},
    {'id': '7', 'name': 'delete_menu', 'role_id': '1', 'keyword': 'delete_menu'},
    {'id': '8', 'name': 'create_menu', 'role_id': '1', 'keyword': 'create_menu'},
    {'id': '9', 'name': 'update_menu', 'role_id': '1', 'keyword': 'update_menu'},
    {'id': '10', 'name': 'view_menu', 'role_id': '1', 'keyword': 'view_menu'},
    {'id': '11', 'name': 'delete_meal_item', 'role_id': '1', 'keyword': 'delete_meal_item'},
    {'id': '12', 'name': 'create_meal_item', 'role_id': '1', 'keyword': 'create_meal_item'},
    {'id': '13', 'name': 'update_meal_item', 'role_id': '1', 'keyword': 'update_meal_item'},
    {'id': '14', 'name': 'view_meal_item', 'role_id': '1', 'keyword': 'view_meal_item'},
    {'id': '15', 'name': 'delete_vendor', 'role_id': '1', 'keyword': 'delete'},
    {'id': '16', 'name': 'create_vendor', 'role_id': '1', 'keyword': 'create'},
    {'id': '17', 'name': 'update_vendor', 'role_id': '1', 'keyword': 'update'},
    {'id': '18', 'name': 'read_vendor', 'role_id': '1', 'keyword': 'read'},
    {'id': '19', 'name': 'delete_menu', 'role_id': '1', 'keyword': 'delete'},
    {'id': '20', 'name': 'create_menu', 'role_id': '1', 'keyword': 'create'},
    {'id': '21', 'name': 'update_menu', 'role_id': '1', 'keyword': 'update'},
    {'id': '22', 'name': 'read_menu', 'role_id': '1', 'keyword': 'read'},
    {'id': '23', 'name': 'delete_meal_item', 'role_id': '1', 'keyword': 'delete'},
    {'id': '24', 'name': 'create_meal_item', 'role_id': '1', 'keyword': 'create'},
    {'id': '25', 'name': 'update_meal_item', 'role_id': '1', 'keyword': 'update'},
    {'id': '26', 'name': 'read_meal_item', 'role_id': '1', 'keyword': 'read'},
    {'id': '27', 'name': 'delete_vendor', 'role_id': '1', 'keyword': 'delete'},
    {'id': '28', 'name': 'create_vendor', 'role_id': '1', 'keyword': 'create'},
    {'id': '29', 'name': 'update_vendor', 'role_id': '1', 'keyword': 'update'},
    {'id': '30', 'name': 'read_vendor', 'role_id': '1', 'keyword': 'read'},
    {'id': '31', 'name': 'delete_vendor_engagement', 'role_id': '1', 'keyword': 'delete'},
    {'id': '32', 'name': 'create_vendor_engagement', 'role_id': '1', 'keyword': 'create'},
    {'id': '33', 'name': 'update_vendor_engagement', 'role_id': '1', 'keyword': 'update'},
    {'id': '34', 'name': 'read_vendor_engagement', 'role_id': '1', 'keyword': 'read'},
    {'id': '35', 'name': 'view_orders', 'role_id': '1', 'keyword': 'view_orders'},
    {'id': '36', 'name': 'view_user_roles', 'role_id': '1', 'keyword': 'view_user_roles'},
    {'id': '37', 'name': 'create_user_roles', 'role_id': '1', 'keyword': 'create_user_roles'},
    {'id': '38', 'name': 'delete_user_roles', 'role_id': '1', 'keyword': 'delete_user_roles'},
]
