version: '3.3'

services:
  postgres:
    image: postgres:11-alpine
    ports:
      - "65432:5432"
    environment:
      - POSTGRES_USER=andela
      - POSTGRES_DB=andela
      - POSTGRES_PASSWORD=andela
  redis:
    image: redis
    command: redis-server
  api:
    build: .
    command: ./runserver.sh
    volumes:
      - .:/usr/andelaeats
    labels:
      org.label-schema.name: "Andela-Eats"
      org.label-schema.description: "Andela Eats API"
      com.label-schema.service-type: "eats-api"
    ports:
      - "4070:4070"
    depends_on:
      - postgres
      - redis
