"""empty message

Revision ID: 1141c05851e6
Revises: 14bd30f1c0d2
Create Date: 2019-08-12 09:31:21.147485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1141c05851e6'
down_revision = '14bd30f1c0d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('menu_template_item_day_id_fkey', 'menu_template_item', type_='foreignkey')
    op.create_foreign_key(None, 'menu_template_item', 'menu_template_weekday', ['day_id'], ['id'])
    op.drop_constraint('menu_template_weekday_day_key', 'menu_template_weekday', type_='unique')
    op.drop_constraint('menu_template_weekday_day_template_id_key', 'menu_template_weekday', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('menu_template_weekday_day_template_id_key', 'menu_template_weekday', ['day', 'template_id'])
    op.create_unique_constraint('menu_template_weekday_day_key', 'menu_template_weekday', ['day'])
    op.drop_constraint(None, 'menu_template_item', type_='foreignkey')
    op.create_foreign_key('menu_template_item_day_id_fkey', 'menu_template_item', 'menu_template_weekday', ['day_id'], ['day'])
    # ### end Alembic commands ###
