"""empty message

Revision ID: 29ba3cf8ba11
Revises: 6c383a309ff8
Create Date: 2019-08-15 13:59:08.804415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29ba3cf8ba11'
down_revision = '6c383a309ff8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menu_template_items_to_protein_items',
    sa.Column('meal_item_id', sa.Integer(), nullable=True),
    sa.Column('menu_template_item_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['meal_item_id'], ['meal_items.id'], ),
    sa.ForeignKeyConstraint(['menu_template_item_id'], ['menu_template_item.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('menu_template_items_to_protein_items')
    # ### end Alembic commands ###
