"""empty message

Revision ID: 449f9f8c5443
Revises: caa3c018a501
Create Date: 2018-11-28 13:00:25.051753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '449f9f8c5443'
down_revision = 'f1e897fca46d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_roles', sa.Column('location_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user_roles', 'locations', ['location_id'], ['id'])
    op.add_column('vendor_engagements', sa.Column('location_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'vendor_engagements', 'locations', ['location_id'], ['id'])
    op.add_column('vendors', sa.Column('location_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'vendors', 'locations', ['location_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vendors', type_='foreignkey')
    op.drop_column('vendors', 'location_id')
    op.drop_constraint(None, 'vendor_engagements', type_='foreignkey')
    op.drop_column('vendor_engagements', 'location_id')
    op.drop_constraint(None, 'user_roles', type_='foreignkey')
    op.drop_column('user_roles', 'location_id')
    # ### end Alembic commands ###
