"""empty message

Revision ID: 459d3bb06df4
Revises: 57771bab95d2
Create Date: 2019-05-01 19:47:54.623926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '459d3bb06df4'
down_revision = '57771bab95d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_roles', sa.Column('email', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_roles', 'email')
    # ### end Alembic commands ###
