"""empty message

Revision ID: 4a83f38b751e
Revises: db64682e20cb
Create Date: 2019-03-26 21:58:04.536111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a83f38b751e'
down_revision = 'db64682e20cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_id', sa.String(length=100), nullable=True))
    op.drop_constraint('users_user_role_id_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'user_role_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_role_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('users_user_role_id_fkey', 'users', 'user_roles', ['user_role_id'], ['id'])
    op.drop_column('users', 'user_id')
    # ### end Alembic commands ###
