"""empty message

Revision ID: 5e16bd3ac7ef
Revises: 8b8be802efc7
Create Date: 2019-01-10 09:39:03.634291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e16bd3ac7ef'
down_revision = '8b8be802efc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('module_name', sa.String(length=100), nullable=True),
    sa.Column('ip_address', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.String(length=100), nullable=True),
    sa.Column('action_type', sa.Enum('create', 'update', 'delete', name='actiontype'), nullable=True),
    sa.Column('action_details', sa.String(length=2000), nullable=True),
    sa.Column('channel', sa.Enum('web', 'slack', 'mobile', name='channels_activity'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activities')
    # ### end Alembic commands ###
