"""empty message

Revision ID: 7422f2159771
Revises: ddc52f2538db
Create Date: 2018-11-18 19:58:30.379096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7422f2159771'
down_revision = 'ddc52f2538db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('status', sa.SMALLINT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
