"""empty message

Revision ID: 75ae28301495
Revises: ded2b997851b
Create Date: 2018-11-13 15:54:32.616102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75ae28301495'
down_revision = 'ded2b997851b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendors', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.alter_column('vendors', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vendors', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_column('vendors', 'is_active')
    # ### end Alembic commands ###
