"""empty message

Revision ID: 7d99c6e2f120
Revises: d4b40ca2e5e5
Create Date: 2018-10-16 14:06:04.311714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d99c6e2f120'
down_revision = 'd4b40ca2e5e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.String(length=100), nullable=True),
    sa.Column('date_booked_for', sa.Date(), nullable=False),
    sa.Column('date_booked', sa.Date(), nullable=True),
    sa.Column('channel', sa.Enum('web', 'slack', 'mobile', name='channels'), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meal_item_orders',
    sa.Column('order_id', sa.SmallInteger(), nullable=False),
    sa.Column('meal_item_id', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['meal_item_id'], ['meal_items.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meal_item_orders')
    op.drop_table('orders')
    # ### end Alembic commands ###
