"""empty message

Revision ID: 87c95ab5c906
Revises: 4a83f38b751e
Create Date: 2019-03-29 14:20:34.515822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87c95ab5c906'
down_revision = '4a83f38b751e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_column('users', 'email')
    op.drop_column('users', 'user_id')
    op.drop_column('users', 'slack_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('slack_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('user_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    # ### end Alembic commands ###
