"""empty message

Revision ID: 8b8be802efc7
Revises: a5b5513d8b9f
Create Date: 2019-01-08 10:00:00.604933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b8be802efc7'
down_revision = 'a5b5513d8b9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_roles', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_roles', 'is_active')
    # ### end Alembic commands ###
