"""empty message

Revision ID: 9142b8d84559
Revises: 76a043f695b1
Create Date: 2018-09-26 23:58:17.914100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9142b8d84559'
down_revision = '76a043f695b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menus', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menus', 'is_deleted')
    # ### end Alembic commands ###
