"""empty message

Revision ID: a5b5513d8b9f
Revises: 449f9f8c5443
Create Date: 2018-12-01 22:14:03.566608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5b5513d8b9f'
down_revision = '449f9f8c5443'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meal_items', sa.Column('location_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'meal_items', 'locations', ['location_id'], ['id'])
    op.add_column('menus', sa.Column('location_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'menus', 'locations', ['location_id'], ['id'])
    op.add_column('orders', sa.Column('location_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'orders', 'locations', ['location_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'location_id')
    op.drop_constraint(None, 'menus', type_='foreignkey')
    op.drop_column('menus', 'location_id')
    op.drop_constraint(None, 'meal_items', type_='foreignkey')
    op.drop_column('meal_items', 'location_id')
    # ### end Alembic commands ###
