"""empty message

Revision ID: b15ee05052f7
Revises: caa3c018a501
Create Date: 2018-11-29 12:03:17.677695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b15ee05052f7'
down_revision = 'caa3c018a501'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('zone', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('locations', 'zone')
    # ### end Alembic commands ###
