"""empty message

Revision ID: b226afe34b77
Revises: a509bcacde2f
Create Date: 2018-10-08 15:48:01.186869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b226afe34b77'
down_revision = 'a509bcacde2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('permissions', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('roles', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('user_roles', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('vendor_engagements', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('vendor_ratings', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('vendors', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendors', 'is_deleted')
    op.drop_column('vendor_ratings', 'is_deleted')
    op.drop_column('vendor_engagements', 'is_deleted')
    op.drop_column('user_roles', 'is_deleted')
    op.drop_column('roles', 'is_deleted')
    op.drop_column('permissions', 'is_deleted')
    op.drop_column('locations', 'is_deleted')
    # ### end Alembic commands ###
