"""empty message

Revision ID: c67d14d172d5
Revises: e2762e4c0b4e
Create Date: 2018-11-26 13:02:28.438735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c67d14d172d5'
down_revision = 'e2762e4c0b4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('menu_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'orders', 'menus', ['menu_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'menu_id')
    # ### end Alembic commands ###
