"""empty message

Revision ID: c7ee67f06053
Revises: 
Create Date: 2019-09-11 15:56:02.482736

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c7ee67f06053'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('city',
    sa.Column('uuid', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('timezone', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_city_name'), 'city', ['name'], unique=True)
    op.create_index(op.f('ix_city_uuid'), 'city', ['uuid'], unique=True)
    op.create_table('meal',
    sa.Column('uuid', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('sides', sa.Integer(), nullable=True),
    sa.Column('proteins', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meal_name'), 'meal', ['name'], unique=True)
    op.create_index(op.f('ix_meal_sides'), 'meal', ['sides'], unique=True)
    op.create_index(op.f('ix_meal_uuid'), 'meal', ['uuid'], unique=True)
    op.create_index('meal_idx', 'meal', ['name', 'sides', 'proteins'], unique=False)
    op.create_table('meal_group',
    sa.Column('uuid', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meal_group_name'), 'meal_group', ['name'], unique=True)
    op.create_index(op.f('ix_meal_group_uuid'), 'meal_group', ['uuid'], unique=True)
    op.create_table('meal_item',
    sa.Column('uuid', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('meal_type', sa.Enum('main', 'side', 'dinner', name='mealtypes'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meal_item_name'), 'meal_item', ['name'], unique=True)
    op.create_index(op.f('ix_meal_item_uuid'), 'meal_item', ['uuid'], unique=True)
    op.create_table('rating_type',
    sa.Column('uuid', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rating_type_name'), 'rating_type', ['name'], unique=True)
    op.create_index(op.f('ix_rating_type_uuid'), 'rating_type', ['uuid'], unique=True)
    op.create_table('user',
    sa.Column('uuid', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('slack_id', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=30), nullable=False),
    sa.Column('last_name', sa.String(length=30), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('roles', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_slack_id'), 'user', ['slack_id'], unique=True)
    op.create_index(op.f('ix_user_uuid'), 'user', ['uuid'], unique=True)
    op.create_table('meal_group_item',
    sa.Column('uuid', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meal_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['meal_group.id'], ),
    sa.ForeignKeyConstraint(['meal_id'], ['meal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meal_group_item_uuid'), 'meal_group_item', ['uuid'], unique=True)
    op.create_index('meal_group_item_idx', 'meal_group_item', ['group_id', 'meal_id'], unique=False)
    op.create_table('meal_items',
    sa.Column('uuid', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meal_id', sa.Integer(), nullable=False),
    sa.Column('meal_item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['meal_id'], ['meal.id'], ),
    sa.ForeignKeyConstraint(['meal_item_id'], ['meal_item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meal_items_uuid'), 'meal_items', ['uuid'], unique=True)
    op.create_index('meal_items_idx', 'meal_items', ['meal_id', 'meal_item_id'], unique=False)
    op.create_table('vendor',
    sa.Column('uuid', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('telephone', sa.String(length=30), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendor_uuid'), 'vendor', ['uuid'], unique=True)
    op.create_table('rating',
    sa.Column('uuid', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rating_type_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rating_type_id'], ['rating_type.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['vendor.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rating_name'), 'rating', ['name'], unique=True)
    op.create_index(op.f('ix_rating_uuid'), 'rating', ['uuid'], unique=True)
    op.create_index('rating_idx', 'rating', ['user_id', 'rating_type_id', 'source_id'], unique=False)
    op.create_table('vendor_engagement',
    sa.Column('uuid', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('finish_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', 'terminated', name='engagementstatus'), nullable=False),
    sa.Column('termination_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendor_engagement_uuid'), 'vendor_engagement', ['uuid'], unique=True)
    op.create_table('meal_vendor_engagement',
    sa.Column('uuid', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meal_id', sa.Integer(), nullable=False),
    sa.Column('vendor_engagement_id', sa.Integer(), nullable=False),
    sa.Column('meal_period', sa.Enum('breakfast', 'lunch', 'dinner', name='mealperiods'), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['meal_id'], ['meal.id'], ),
    sa.ForeignKeyConstraint(['vendor_engagement_id'], ['vendor_engagement.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meal_vendor_engagement_uuid'), 'meal_vendor_engagement', ['uuid'], unique=True)
    op.create_index('meal_vendor_engagement_idx', 'meal_vendor_engagement', ['meal_id', 'vendor_engagement_id', 'meal_period'], unique=False)
    op.create_table('meal_service',
    sa.Column('uuid', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meal_vendor_engagement_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['city.id'], ),
    sa.ForeignKeyConstraint(['meal_vendor_engagement_id'], ['meal_vendor_engagement.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meal_service_uuid'), 'meal_service', ['uuid'], unique=True)
    op.create_index('meal_service_idx', 'meal_service', ['user_id', 'city_id', 'meal_vendor_engagement_id'], unique=False)
    op.create_table('order',
    sa.Column('uuid', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('meal_vendor_engagement_id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('booked', 'collected', 'cancelled', name='orderstatus'), nullable=True),
    sa.Column('channel', sa.Enum('web', 'slack', 'mobile', name='channels'), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['city.id'], ),
    sa.ForeignKeyConstraint(['meal_vendor_engagement_id'], ['meal_vendor_engagement.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_uuid'), 'order', ['uuid'], unique=True)
    op.create_index('order_idx', 'order', ['user_id', 'meal_vendor_engagement_id', 'city_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('order_idx', table_name='order')
    op.drop_index(op.f('ix_order_uuid'), table_name='order')
    op.drop_table('order')
    op.drop_index('meal_service_idx', table_name='meal_service')
    op.drop_index(op.f('ix_meal_service_uuid'), table_name='meal_service')
    op.drop_table('meal_service')
    op.drop_index('meal_vendor_engagement_idx', table_name='meal_vendor_engagement')
    op.drop_index(op.f('ix_meal_vendor_engagement_uuid'), table_name='meal_vendor_engagement')
    op.drop_table('meal_vendor_engagement')
    op.drop_index(op.f('ix_vendor_engagement_uuid'), table_name='vendor_engagement')
    op.drop_table('vendor_engagement')
    op.drop_index('rating_idx', table_name='rating')
    op.drop_index(op.f('ix_rating_uuid'), table_name='rating')
    op.drop_index(op.f('ix_rating_name'), table_name='rating')
    op.drop_table('rating')
    op.drop_index(op.f('ix_vendor_uuid'), table_name='vendor')
    op.drop_table('vendor')
    op.drop_index('meal_items_idx', table_name='meal_items')
    op.drop_index(op.f('ix_meal_items_uuid'), table_name='meal_items')
    op.drop_table('meal_items')
    op.drop_index('meal_group_item_idx', table_name='meal_group_item')
    op.drop_index(op.f('ix_meal_group_item_uuid'), table_name='meal_group_item')
    op.drop_table('meal_group_item')
    op.drop_index(op.f('ix_user_uuid'), table_name='user')
    op.drop_index(op.f('ix_user_slack_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_rating_type_uuid'), table_name='rating_type')
    op.drop_index(op.f('ix_rating_type_name'), table_name='rating_type')
    op.drop_table('rating_type')
    op.drop_index(op.f('ix_meal_item_uuid'), table_name='meal_item')
    op.drop_index(op.f('ix_meal_item_name'), table_name='meal_item')
    op.drop_table('meal_item')
    op.drop_index(op.f('ix_meal_group_uuid'), table_name='meal_group')
    op.drop_index(op.f('ix_meal_group_name'), table_name='meal_group')
    op.drop_table('meal_group')
    op.drop_index('meal_idx', table_name='meal')
    op.drop_index(op.f('ix_meal_uuid'), table_name='meal')
    op.drop_index(op.f('ix_meal_sides'), table_name='meal')
    op.drop_index(op.f('ix_meal_name'), table_name='meal')
    op.drop_table('meal')
    op.drop_index(op.f('ix_city_uuid'), table_name='city')
    op.drop_index(op.f('ix_city_name'), table_name='city')
    op.drop_table('city')
    # ### end Alembic commands ###
