"""vendor average rating

Revision ID: ca00580bfe83
Revises: 54c19e671c54
Create Date: 2019-03-21 10:54:56.031723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca00580bfe83'
down_revision = '54c19e671c54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendors', sa.Column('average_rating', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendors', 'average_rating')
    # ### end Alembic commands ###
