"""empty message

Revision ID: d4c92d1d467d
Revises: 449f9f8c5443
Create Date: 2018-12-01 04:03:43.142137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4c92d1d467d'
down_revision = '449f9f8c5443'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('zone', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('locations', 'zone')
    # ### end Alembic commands ###
