"""empty message

Revision ID: e2762e4c0b4e
Revises: 7422f2159771
Create Date: 2018-11-18 19:59:09.521696

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
from sqlalchemy.dialects import postgresql

revision = 'e2762e4c0b4e'
down_revision = '7422f2159771'
branch_labels = None
depends_on = None


def upgrade():
	# ### commands auto generated by Alembic - please adjust! ###
	order_status = postgresql.ENUM('booked', 'collected', 'cancelled', name='order_status')
	order_status.create(op.get_bind())
	op.add_column('orders', sa.Column('order_status', sa.Enum('booked', 'collected', 'cancelled', name='order_status'),
									nullable=True))
	# ### end Alembic commands ###


def downgrade():
	# ### commands auto generated by Alembic - please adjust! ###
	op.drop_column('orders', 'order_status')

	order_status = postgresql.ENUM('booked', 'collected', 'cancelled', name='order_status')
	order_status.drop(op.get_bind())
	# ### end Alembic commands ###
