"""empty message

Revision ID: e874ae8a2051
Revises: 87c95ab5c906
Create Date: 2019-03-29 14:20:59.210367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e874ae8a2051'
down_revision = '87c95ab5c906'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('slack_id', sa.String(), nullable=False))
    op.add_column('users', sa.Column('user_id', sa.String(length=100), nullable=True))
    op.create_unique_constraint(None, 'users', ['slack_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'user_id')
    op.drop_column('users', 'slack_id')
    # ### end Alembic commands ###
