"""empty message

Revision ID: ed82f3ebd841
Revises: e0d88514c2ca
Create Date: 2018-09-17 00:43:35.554700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed82f3ebd841'
down_revision = 'e0d88514c2ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendor_ratings', sa.Column('channel', sa.String(length=100), nullable=True))
    op.drop_constraint('vendor_ratings_vendor_engagement_id_fkey', 'vendor_ratings', type_='foreignkey')
    op.drop_column('vendor_ratings', 'order_id')
    op.drop_column('vendor_ratings', 'vendor_engagement_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendor_ratings', sa.Column('vendor_engagement_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('vendor_ratings', sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('vendor_ratings_vendor_engagement_id_fkey', 'vendor_ratings', 'vendor_engagements', ['vendor_engagement_id'], ['id'])
    op.drop_column('vendor_ratings', 'channel')
    # ### end Alembic commands ###
